# Generated by Django 4.1.6 on 2023-08-16 09:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetMediaFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Image ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, max_length=254, null=True, upload_to="pet_media/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeghtMeasurement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name="petprofile",
            name="height",
        ),
        migrations.RemoveField(
            model_name="petprofile",
            name="pet_age",
        ),
        migrations.AddField(
            model_name="petprofile",
            name="pet_dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="petprofile",
            name="weight",
            field=models.FloatField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name="PetImage",
        ),
        migrations.AddField(
            model_name="petmediafile",
            name="pet_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_files",
                to="pet.petprofile",
            ),
        ),
        migrations.AddField(
            model_name="petprofile",
            name="weight_measurement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pet.weghtmeasurement",
            ),
        ),
    ]
