# Generated by Django 4.1.6 on 2023-08-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0003_rename_weghtmeasurement_weightmeasurement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="petmediafile",
            name="featured",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="petprofile",
            name="number_of_nails",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
