# Generated by Django 4.1.6 on 2023-08-17 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0004_petmediafile_featured_petprofile_number_of_nails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petbreed",
            name="show_mixed_breeds",
        ),
    ]
