# Generated by Django 4.1.6 on 2023-08-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0005_remove_petbreed_show_mixed_breeds"),
    ]

    operations = [
        migrations.AddField(
            model_name="petprofile",
            name="featured",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
