# Generated by Django 4.1.6 on 2023-08-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0006_petprofile_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petmediafile",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="petprofile",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
