# Generated by Django 4.1.6 on 2023-08-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0007_alter_petmediafile_featured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petmediafile",
            name="pet_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_files",
                to="pet.petprofile",
            ),
        ),
    ]
