# Generated by Django 4.1.6 on 2023-08-24 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0008_alter_petmediafile_pet_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petprofile",
            name="featured",
        ),
    ]
