# Generated by Django 4.1.6 on 2023-08-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_publisher_name_alter_blog_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="excerpt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
