# Generated by Django 4.1.6 on 2023-08-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favourite_pet",
            field=models.ManyToManyField(
                related_name="favourite_pet", to="pet.petprofile"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="like",
            field=models.ManyToManyField(related_name="like", to="pet.petprofile"),
        ),
    ]
